// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VysyxSoCFull.h for the primary calling header

#ifndef VERILATED_VYSYXSOCFULL_YSYX_25080218_H_
#define VERILATED_VYSYXSOCFULL_YSYX_25080218_H_  // guard

#include "verilated.h"


class VysyxSoCFull__Syms;

class alignas(VL_CACHE_LINE_BYTES) VysyxSoCFull_ysyx_25080218 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        CData/*0:0*/ valid_to_lsu;
        CData/*0:0*/ IDU_init__DOT__imm_is_I;
        CData/*0:0*/ IDU_init__DOT__imm_is_J;
        CData/*0:0*/ IDU_init__DOT__imm_is_B;
        CData/*0:0*/ IDU_init__DOT__imm_is_S;
        CData/*0:0*/ IDU_init__DOT__imm_is_U;
        CData/*0:0*/ IDU_init__DOT__imm_is_R;
        VL_IN8(io_interrupt,0,0);
        VL_IN8(io_master_awready,0,0);
        VL_OUT8(io_master_awvalid,0,0);
        VL_OUT8(io_master_awid,3,0);
        VL_OUT8(io_master_awlen,7,0);
        VL_OUT8(io_master_awsize,2,0);
        VL_OUT8(io_master_awburst,1,0);
        VL_IN8(io_master_wready,0,0);
        VL_OUT8(io_master_wvalid,0,0);
        VL_OUT8(io_master_wstrb,3,0);
        VL_OUT8(io_master_wlast,0,0);
        VL_OUT8(io_master_bready,0,0);
        VL_IN8(io_master_bvalid,0,0);
        VL_IN8(io_master_bresp,1,0);
        VL_IN8(io_master_bid,3,0);
        VL_IN8(io_master_arready,0,0);
        VL_OUT8(io_master_arvalid,0,0);
        VL_OUT8(io_master_arid,3,0);
        VL_OUT8(io_master_arlen,7,0);
        VL_OUT8(io_master_arsize,2,0);
        VL_OUT8(io_master_arburst,1,0);
        VL_OUT8(io_master_rready,0,0);
        VL_IN8(io_master_rvalid,0,0);
        VL_IN8(io_master_rresp,1,0);
        VL_IN8(io_master_rlast,0,0);
        VL_IN8(io_master_rid,3,0);
        VL_OUT8(io_slave_awready,0,0);
        VL_IN8(io_slave_awvalid,0,0);
        VL_IN8(io_slave_awid,3,0);
        VL_IN8(io_slave_awlen,7,0);
        VL_IN8(io_slave_awsize,2,0);
        VL_IN8(io_slave_awburst,1,0);
        VL_OUT8(io_slave_wready,0,0);
        VL_IN8(io_slave_wvalid,0,0);
        VL_IN8(io_slave_wstrb,3,0);
        VL_IN8(io_slave_wlast,0,0);
        VL_IN8(io_slave_bready,0,0);
        VL_OUT8(io_slave_bvalid,0,0);
        VL_OUT8(io_slave_bresp,1,0);
        VL_OUT8(io_slave_bid,3,0);
        VL_OUT8(io_slave_arready,0,0);
        VL_IN8(io_slave_arvalid,0,0);
        VL_IN8(io_slave_arid,3,0);
        VL_IN8(io_slave_arlen,7,0);
        VL_IN8(io_slave_arsize,2,0);
        VL_IN8(io_slave_arburst,1,0);
        VL_IN8(io_slave_rready,0,0);
        VL_OUT8(io_slave_rvalid,0,0);
        VL_OUT8(io_slave_rresp,1,0);
        VL_OUT8(io_slave_rlast,0,0);
        VL_OUT8(io_slave_rid,3,0);
        CData/*4:0*/ gpr_waddr;
        CData/*0:0*/ gpr_we;
        CData/*0:0*/ rd_we;
        CData/*4:0*/ rd;
    };
    struct {
        CData/*0:0*/ is_jump;
        CData/*4:0*/ load_ctrl;
        CData/*2:0*/ store_ctrl;
        CData/*5:0*/ branch_ctrl;
        CData/*0:0*/ is_ecall_mret;
        CData/*0:0*/ Ifu2Idu_valid;
        CData/*0:0*/ Idu2Ifu_ready;
        CData/*0:0*/ valid_to_exu;
        CData/*0:0*/ ready_from_exu;
        CData/*0:0*/ branch_taken;
        CData/*0:0*/ m0_awvalid;
        CData/*0:0*/ m0_awready;
        CData/*3:0*/ m0_wstrb;
        CData/*0:0*/ m0_wvalid;
        CData/*0:0*/ m0_wready;
        CData/*1:0*/ m0_bresp;
        CData/*0:0*/ m0_bvalid;
        CData/*0:0*/ m0_bready;
        CData/*0:0*/ m0_arvalid;
        CData/*0:0*/ m0_arready;
        CData/*1:0*/ m0_rresp;
        CData/*0:0*/ m0_rvalid;
        CData/*0:0*/ m0_rready;
        CData/*0:0*/ ready_from_lsu;
        CData/*0:0*/ valid_to_wbu;
        CData/*0:0*/ ready_from_wbu;
        CData/*0:0*/ commit;
        CData/*0:0*/ m1_awvalid;
        CData/*0:0*/ m1_awready;
        CData/*3:0*/ m1_wstrb;
        CData/*0:0*/ m1_wvalid;
        CData/*0:0*/ m1_wready;
        CData/*1:0*/ m1_bresp;
        CData/*0:0*/ m1_bvalid;
        CData/*0:0*/ m1_bready;
        CData/*0:0*/ m1_arvalid;
        CData/*0:0*/ m1_arready;
        CData/*1:0*/ m1_rresp;
        CData/*0:0*/ m1_rvalid;
        CData/*0:0*/ m1_rready;
        CData/*0:0*/ s0_awvalid;
        CData/*0:0*/ s0_awready;
        CData/*3:0*/ s0_wstrb;
        CData/*0:0*/ s0_wvalid;
        CData/*0:0*/ s0_wready;
        CData/*1:0*/ s0_bresp;
        CData/*0:0*/ s0_bvalid;
        CData/*0:0*/ s0_bready;
        CData/*0:0*/ s0_arvalid;
        CData/*0:0*/ s0_arready;
        CData/*1:0*/ s0_rresp;
        CData/*0:0*/ s0_rvalid;
        CData/*0:0*/ s0_rready;
        CData/*0:0*/ s1_awvalid;
        CData/*0:0*/ s1_awready;
        CData/*3:0*/ s1_wstrb;
        CData/*0:0*/ s1_wvalid;
        CData/*0:0*/ s1_wready;
        CData/*1:0*/ s1_bresp;
        CData/*0:0*/ s1_bvalid;
        CData/*0:0*/ s1_bready;
        CData/*0:0*/ s1_arvalid;
        CData/*0:0*/ s1_arready;
        CData/*1:0*/ s1_rresp;
    };
    struct {
        CData/*0:0*/ s1_rvalid;
        CData/*0:0*/ s1_rready;
        CData/*1:0*/ cache_rresp;
        CData/*0:0*/ cache_rvalid;
        CData/*0:0*/ cache_rready;
        CData/*0:0*/ cache_arvalid;
        CData/*0:0*/ cache_arready;
        CData/*0:0*/ s2_awvalid;
        CData/*0:0*/ s2_awready;
        CData/*3:0*/ s2_wstrb;
        CData/*0:0*/ s2_wvalid;
        CData/*0:0*/ s2_wready;
        CData/*1:0*/ s2_bresp;
        CData/*0:0*/ s2_bvalid;
        CData/*0:0*/ s2_bready;
        CData/*0:0*/ s2_arvalid;
        CData/*0:0*/ s2_arready;
        CData/*1:0*/ s2_rresp;
        CData/*0:0*/ s2_rvalid;
        CData/*0:0*/ s2_rready;
        CData/*0:0*/ IDU_init__DOT__clk;
        CData/*0:0*/ IDU_init__DOT__rst;
        CData/*4:0*/ IDU_init__DOT__gpr_waddr;
        CData/*0:0*/ IDU_init__DOT__gpr_we;
        CData/*0:0*/ IDU_init__DOT__valid_from_ifu;
        CData/*0:0*/ IDU_init__DOT__ready_from_exu;
        CData/*0:0*/ IDU_init__DOT__rd_we;
        CData/*4:0*/ IDU_init__DOT__rd;
        CData/*0:0*/ IDU_init__DOT__is_jump;
        CData/*4:0*/ IDU_init__DOT__load_ctrl;
        CData/*2:0*/ IDU_init__DOT__store_ctrl;
        CData/*5:0*/ IDU_init__DOT__branch_ctrl;
        CData/*0:0*/ IDU_init__DOT__is_ecall_mret;
        CData/*0:0*/ IDU_init__DOT__ready_to_ifu;
        CData/*0:0*/ IDU_init__DOT__valid_to_exu;
        CData/*6:0*/ IDU_init__DOT__opcode;
        CData/*4:0*/ IDU_init__DOT__src1;
        CData/*4:0*/ IDU_init__DOT__src2;
        CData/*2:0*/ IDU_init__DOT__fun3;
        CData/*6:0*/ IDU_init__DOT__fun7;
        CData/*4:0*/ IDU_init__DOT__shamt;
        CData/*0:0*/ IDU_init__DOT__is_break;
        CData/*0:0*/ IDU_init__DOT__is_auipc;
        CData/*0:0*/ IDU_init__DOT__is_lui;
        CData/*0:0*/ IDU_init__DOT__is_jal;
        CData/*0:0*/ IDU_init__DOT__is_jalr;
        CData/*0:0*/ IDU_init__DOT__is_and;
        CData/*0:0*/ IDU_init__DOT__is_or;
        CData/*0:0*/ IDU_init__DOT__is_xor;
        CData/*0:0*/ IDU_init__DOT__is_sub;
        CData/*0:0*/ IDU_init__DOT__is_sll;
        CData/*0:0*/ IDU_init__DOT__is_srl;
        CData/*0:0*/ IDU_init__DOT__is_sra;
        CData/*0:0*/ IDU_init__DOT__is_slt;
        CData/*0:0*/ IDU_init__DOT__is_sltu;
        CData/*0:0*/ IDU_init__DOT__is_lb;
        CData/*0:0*/ IDU_init__DOT__is_lh;
        CData/*0:0*/ IDU_init__DOT__is_lw;
        CData/*0:0*/ IDU_init__DOT__is_lhu;
        CData/*0:0*/ IDU_init__DOT__is_lbu;
        CData/*0:0*/ IDU_init__DOT__is_sw;
        CData/*0:0*/ IDU_init__DOT__is_sh;
        CData/*0:0*/ IDU_init__DOT__is_sb;
        CData/*0:0*/ IDU_init__DOT__is_bne;
    };
    struct {
        CData/*0:0*/ IDU_init__DOT__is_beq;
        CData/*0:0*/ IDU_init__DOT__is_blt;
        CData/*0:0*/ IDU_init__DOT__is_bge;
        CData/*0:0*/ IDU_init__DOT__is_bltu;
        CData/*0:0*/ IDU_init__DOT__is_bgeu;
        CData/*0:0*/ IDU_init__DOT__is_mstatus;
        CData/*0:0*/ IDU_init__DOT__is_mtvec;
        CData/*0:0*/ IDU_init__DOT__is_mepc;
        CData/*0:0*/ IDU_init__DOT__is_mcause;
        CData/*0:0*/ IDU_init__DOT__is_mvendorid;
        CData/*0:0*/ IDU_init__DOT__is_marchid;
        CData/*0:0*/ IDU_init__DOT__is_csrrw;
        CData/*0:0*/ IDU_init__DOT__is_csrrs;
        CData/*0:0*/ IDU_init__DOT__is_csr;
        CData/*0:0*/ IDU_init__DOT__is_ecall;
        CData/*0:0*/ IDU_init__DOT__is_mret;
        CData/*0:0*/ IDU_init__DOT____VdfgRegularize_h80d369ef_0_0;
        CData/*0:0*/ IDU_init__DOT____VdfgRegularize_h80d369ef_0_10;
        CData/*0:0*/ IDU_init__DOT____VdfgRegularize_h80d369ef_0_14;
        CData/*0:0*/ IDU_init__DOT____VdfgRegularize_h80d369ef_0_15;
        CData/*0:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__clk;
        CData/*0:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__rst;
        CData/*4:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__gpr_waddr;
        CData/*0:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__gpr_we;
        CData/*4:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__gpr_raddr1;
        CData/*4:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__gpr_raddr2;
        CData/*0:0*/ IFU_init__DOT__clk;
        CData/*0:0*/ IFU_init__DOT__rst;
        CData/*0:0*/ IFU_init__DOT__is_jump;
        CData/*0:0*/ IFU_init__DOT__branch_taken;
        CData/*0:0*/ IFU_init__DOT__is_ecall_mret;
        CData/*0:0*/ IFU_init__DOT__ready;
        CData/*0:0*/ IFU_init__DOT__valid;
        CData/*0:0*/ IFU_init__DOT__ARVALID;
        CData/*0:0*/ IFU_init__DOT__ARREADY;
        CData/*1:0*/ IFU_init__DOT__RRESP;
        CData/*0:0*/ IFU_init__DOT__RVALID;
        CData/*0:0*/ IFU_init__DOT__RREADY;
        CData/*0:0*/ IFU_init__DOT__valid_rst;
        CData/*2:0*/ IFU_init__DOT__state;
        CData/*5:0*/ EXU_init__DOT__branch_ctrl;
        CData/*0:0*/ EXU_init__DOT__valid_from_idu;
        CData/*0:0*/ EXU_init__DOT__read_from_lsu;
        CData/*0:0*/ EXU_init__DOT__branch_taken;
        CData/*0:0*/ EXU_init__DOT__ready_to_idu;
        CData/*0:0*/ EXU_init__DOT__valid_to_lsu;
        CData/*0:0*/ EXU_init__DOT__op_add;
        CData/*0:0*/ EXU_init__DOT__op_sub;
        CData/*0:0*/ EXU_init__DOT__op_and;
        CData/*0:0*/ EXU_init__DOT__op_or;
        CData/*0:0*/ EXU_init__DOT__op_xor;
        CData/*0:0*/ EXU_init__DOT__op_sll;
        CData/*0:0*/ EXU_init__DOT__op_srl;
        CData/*0:0*/ EXU_init__DOT__op_sra;
        CData/*0:0*/ EXU_init__DOT__op_lui;
        CData/*0:0*/ EXU_init__DOT__op_slt;
        CData/*0:0*/ EXU_init__DOT__op_sltu;
        CData/*0:0*/ EXU_init__DOT__carry_in;
        CData/*0:0*/ EXU_init__DOT__is_beq;
        CData/*0:0*/ EXU_init__DOT__is_bne;
        CData/*0:0*/ EXU_init__DOT__is_blt;
        CData/*0:0*/ EXU_init__DOT__is_bge;
        CData/*0:0*/ EXU_init__DOT__is_bltu;
        CData/*0:0*/ EXU_init__DOT__is_bgeu;
    };
    struct {
        CData/*0:0*/ EXU_init__DOT__equal;
        CData/*0:0*/ EXU_init__DOT__less_than_signed;
        CData/*0:0*/ EXU_init__DOT__less_than_unsigned;
        CData/*4:0*/ EXU_init__DOT____VdfgRegularize_he932f07c_0_0;
        CData/*0:0*/ MAU_init__DOT__clk;
        CData/*0:0*/ MAU_init__DOT__rst;
        CData/*0:0*/ MAU_init__DOT__wen;
        CData/*0:0*/ MAU_init__DOT__valid_from_exu;
        CData/*0:0*/ MAU_init__DOT__ready_to_exu;
        CData/*0:0*/ MAU_init__DOT__valid_to_wbu;
        CData/*0:0*/ MAU_init__DOT__ready_from_wbu;
        CData/*4:0*/ MAU_init__DOT__load_ctrl;
        CData/*2:0*/ MAU_init__DOT__store_ctrl;
        CData/*0:0*/ MAU_init__DOT__AWVALID;
        CData/*0:0*/ MAU_init__DOT__AWREADY;
        CData/*3:0*/ MAU_init__DOT__WSTRB;
        CData/*0:0*/ MAU_init__DOT__WVALID;
        CData/*0:0*/ MAU_init__DOT__WREADY;
        CData/*1:0*/ MAU_init__DOT__BRESP;
        CData/*0:0*/ MAU_init__DOT__BVALID;
        CData/*0:0*/ MAU_init__DOT__BREADY;
        CData/*0:0*/ MAU_init__DOT__ARVALID;
        CData/*0:0*/ MAU_init__DOT__ARREADY;
        CData/*1:0*/ MAU_init__DOT__RRESP;
        CData/*0:0*/ MAU_init__DOT__RVALID;
        CData/*0:0*/ MAU_init__DOT__RREADY;
        CData/*0:0*/ MAU_init__DOT__lsu_reqValid;
        CData/*0:0*/ MAU_init__DOT__is_mem_op;
        CData/*0:0*/ MAU_init__DOT__load_valid;
        CData/*0:0*/ MAU_init__DOT__store_valid;
        CData/*3:0*/ MAU_init__DOT__wmask;
        CData/*2:0*/ MAU_init__DOT__state;
        CData/*0:0*/ MAU_init__DOT__done;
        CData/*0:0*/ MAU_init__DOT__aw_done;
        CData/*0:0*/ MAU_init__DOT__w_done;
        CData/*0:0*/ MAU_init__DOT____VdfgRegularize_h3fdffd83_0_0;
        CData/*0:0*/ WBU_init__DOT__rd_we;
        CData/*4:0*/ WBU_init__DOT__rd;
        CData/*4:0*/ WBU_init__DOT__load_ctrl;
        CData/*0:0*/ WBU_init__DOT__gpr_we;
        CData/*0:0*/ WBU_init__DOT__valid_from_lsu;
        CData/*4:0*/ WBU_init__DOT__gpr_waddr;
        CData/*0:0*/ WBU_init__DOT__ready_from_wbu;
        CData/*0:0*/ Cache_init__DOT__clock;
        CData/*0:0*/ Cache_init__DOT__reset;
        CData/*0:0*/ Cache_init__DOT__out_arvalid;
        CData/*0:0*/ Cache_init__DOT__out_arready;
        CData/*0:0*/ Cache_init__DOT__in_arvalid;
        CData/*0:0*/ Cache_init__DOT__in_arready;
        CData/*0:0*/ Cache_init__DOT__in_rready;
        CData/*0:0*/ Cache_init__DOT__in_rvalid;
        CData/*1:0*/ Cache_init__DOT__in_rresp;
        CData/*0:0*/ Cache_init__DOT__out_rready;
        CData/*0:0*/ Cache_init__DOT__out_rvalid;
        CData/*1:0*/ Cache_init__DOT__out_rresp;
        CData/*3:0*/ Cache_init__DOT__index;
        CData/*3:0*/ Cache_init__DOT__state;
        CData/*0:0*/ xbar_init__DOT__clk;
        CData/*0:0*/ xbar_init__DOT__rst;
        CData/*0:0*/ xbar_init__DOT__m1_awvalid;
        CData/*0:0*/ xbar_init__DOT__m1_awready;
        CData/*3:0*/ xbar_init__DOT__m1_wstrb;
        CData/*0:0*/ xbar_init__DOT__m1_wvalid;
        CData/*0:0*/ xbar_init__DOT__m1_wready;
    };
    struct {
        CData/*1:0*/ xbar_init__DOT__m1_bresp;
        CData/*0:0*/ xbar_init__DOT__m1_bvalid;
        CData/*0:0*/ xbar_init__DOT__m1_bready;
        CData/*0:0*/ xbar_init__DOT__m1_arvalid;
        CData/*0:0*/ xbar_init__DOT__m1_arready;
        CData/*1:0*/ xbar_init__DOT__m1_rresp;
        CData/*0:0*/ xbar_init__DOT__m1_rvalid;
        CData/*0:0*/ xbar_init__DOT__m1_rready;
        CData/*0:0*/ xbar_init__DOT__m0_awvalid;
        CData/*0:0*/ xbar_init__DOT__m0_awready;
        CData/*3:0*/ xbar_init__DOT__m0_wstrb;
        CData/*0:0*/ xbar_init__DOT__m0_wvalid;
        CData/*0:0*/ xbar_init__DOT__m0_wready;
        CData/*1:0*/ xbar_init__DOT__m0_bresp;
        CData/*0:0*/ xbar_init__DOT__m0_bvalid;
        CData/*0:0*/ xbar_init__DOT__m0_bready;
        CData/*0:0*/ xbar_init__DOT__m0_arvalid;
        CData/*0:0*/ xbar_init__DOT__m0_arready;
        CData/*1:0*/ xbar_init__DOT__m0_rresp;
        CData/*0:0*/ xbar_init__DOT__m0_rvalid;
        CData/*0:0*/ xbar_init__DOT__m0_rready;
        CData/*0:0*/ xbar_init__DOT__s0_awvalid;
        CData/*0:0*/ xbar_init__DOT__s0_awready;
        CData/*3:0*/ xbar_init__DOT__s0_wstrb;
        CData/*0:0*/ xbar_init__DOT__s0_wvalid;
        CData/*0:0*/ xbar_init__DOT__s0_wready;
        CData/*1:0*/ xbar_init__DOT__s0_bresp;
        CData/*0:0*/ xbar_init__DOT__s0_bvalid;
        CData/*0:0*/ xbar_init__DOT__s0_bready;
        CData/*0:0*/ xbar_init__DOT__s0_arvalid;
        CData/*0:0*/ xbar_init__DOT__s0_arready;
        CData/*1:0*/ xbar_init__DOT__s0_rresp;
        CData/*0:0*/ xbar_init__DOT__s0_rvalid;
        CData/*0:0*/ xbar_init__DOT__s0_rready;
        CData/*0:0*/ xbar_init__DOT__s1_awvalid;
        CData/*0:0*/ xbar_init__DOT__s1_awready;
        CData/*3:0*/ xbar_init__DOT__s1_wstrb;
        CData/*0:0*/ xbar_init__DOT__s1_wvalid;
        CData/*0:0*/ xbar_init__DOT__s1_wready;
        CData/*1:0*/ xbar_init__DOT__s1_bresp;
        CData/*0:0*/ xbar_init__DOT__s1_bvalid;
        CData/*0:0*/ xbar_init__DOT__s1_bready;
        CData/*0:0*/ xbar_init__DOT__s1_arvalid;
        CData/*0:0*/ xbar_init__DOT__s1_arready;
        CData/*1:0*/ xbar_init__DOT__s1_rresp;
        CData/*0:0*/ xbar_init__DOT__s1_rvalid;
        CData/*0:0*/ xbar_init__DOT__s1_rready;
        CData/*0:0*/ xbar_init__DOT__m0_r_s0;
        CData/*0:0*/ xbar_init__DOT__m0_r_s1;
        CData/*0:0*/ xbar_init__DOT__m1_r_s0;
        CData/*0:0*/ xbar_init__DOT__m1_r_s1;
        CData/*0:0*/ xbar_init__DOT__m0_rreq_s0;
        CData/*0:0*/ xbar_init__DOT__m0_rreq_s1;
        CData/*0:0*/ xbar_init__DOT__m1_rreq_s0;
        CData/*0:0*/ xbar_init__DOT__m1_rreq_s1;
        CData/*0:0*/ xbar_init__DOT__m0_w_s0;
        CData/*0:0*/ xbar_init__DOT__m0_w_s1;
        CData/*0:0*/ xbar_init__DOT__m1_w_s0;
        CData/*0:0*/ xbar_init__DOT__m1_w_s1;
        CData/*0:0*/ xbar_init__DOT__s0_r_owner;
        CData/*0:0*/ xbar_init__DOT__s0_r_busy;
        CData/*0:0*/ xbar_init__DOT__s1_r_owner;
        CData/*0:0*/ xbar_init__DOT__s1_r_busy;
        CData/*0:0*/ xbar_init__DOT__s0_w_busy;
    };
    struct {
        CData/*0:0*/ xbar_init__DOT__s1_w_busy;
        CData/*0:0*/ clint_init__DOT__clk;
        CData/*0:0*/ clint_init__DOT__rst;
        CData/*0:0*/ clint_init__DOT__s_awvalid;
        CData/*0:0*/ clint_init__DOT__s_awready;
        CData/*3:0*/ clint_init__DOT__s_wstrb;
        CData/*0:0*/ clint_init__DOT__s_wvalid;
        CData/*0:0*/ clint_init__DOT__s_wready;
        CData/*1:0*/ clint_init__DOT__s_bresp;
        CData/*0:0*/ clint_init__DOT__s_bvalid;
        CData/*0:0*/ clint_init__DOT__s_bready;
        CData/*0:0*/ clint_init__DOT__s_arvalid;
        CData/*0:0*/ clint_init__DOT__s_arready;
        CData/*1:0*/ clint_init__DOT__s_rresp;
        CData/*0:0*/ clint_init__DOT__s_rvalid;
        CData/*0:0*/ clint_init__DOT__s_rready;
        CData/*0:0*/ clint_init__DOT__s_busy;
        CData/*0:0*/ __Vdly__m1_arvalid;
        CData/*0:0*/ __Vdly__m1_awvalid;
        CData/*0:0*/ __Vdly__m1_wvalid;
        CData/*0:0*/ __Vdly__m0_arvalid;
        CData/*0:0*/ __Vdly__s1_rvalid;
        SData/*11:0*/ imm;
        SData/*11:0*/ alu_op;
        SData/*11:0*/ IDU_init__DOT__imm;
        SData/*11:0*/ IDU_init__DOT__alu_op;
        SData/*11:0*/ IDU_init__DOT__csr_addr;
        SData/*11:0*/ EXU_init__DOT__alu_op;
        SData/*10:0*/ Cache_init__DOT__cache_hit;
        VL_OUT(io_master_awaddr,31,0);
        VL_OUT(io_master_wdata,31,0);
        VL_OUT(io_master_araddr,31,0);
        VL_IN(io_master_rdata,31,0);
        VL_IN(io_slave_awaddr,31,0);
        VL_IN(io_slave_wdata,31,0);
        VL_IN(io_slave_araddr,31,0);
        VL_OUT(io_slave_rdata,31,0);
        IData/*31:0*/ pc;
        IData/*31:0*/ inst;
        IData/*31:0*/ gpr_wdata;
        IData/*31:0*/ alu_src1;
        IData/*31:0*/ alu_src2;
        IData/*31:0*/ next_pc_jump;
        IData/*31:0*/ pc_wire;
        IData/*31:0*/ npc;
        IData/*31:0*/ dnpc;
        IData/*31:0*/ rs2;
        IData/*31:0*/ rs1;
        IData/*31:0*/ branch_pc;
        IData/*31:0*/ next_pc_csr;
        IData/*31:0*/ __Vcellinp__IDU_init__inst;
        IData/*31:0*/ m0_awaddr;
        IData/*31:0*/ m0_wdata;
        IData/*31:0*/ m0_araddr;
        IData/*31:0*/ m0_rdata;
        IData/*31:0*/ alu_result;
        IData/*31:0*/ rdata;
        IData/*31:0*/ m1_awaddr;
        IData/*31:0*/ m1_wdata;
        IData/*31:0*/ m1_araddr;
        IData/*31:0*/ m1_rdata;
        IData/*31:0*/ s0_awaddr;
        IData/*31:0*/ s0_wdata;
        IData/*31:0*/ s0_araddr;
    };
    struct {
        IData/*31:0*/ s0_rdata;
        IData/*31:0*/ s1_awaddr;
        IData/*31:0*/ s1_wdata;
        IData/*31:0*/ s1_araddr;
        IData/*31:0*/ s1_rdata;
        IData/*31:0*/ cache_rdata;
        IData/*31:0*/ cache_araddr;
        IData/*31:0*/ s2_awaddr;
        IData/*31:0*/ s2_wdata;
        IData/*31:0*/ s2_araddr;
        IData/*31:0*/ s2_rdata;
        IData/*31:0*/ IDU_init__DOT__pc;
        IData/*31:0*/ IDU_init__DOT__inst;
        IData/*31:0*/ IDU_init__DOT__gpr_wdata;
        IData/*31:0*/ IDU_init__DOT__alu_src1;
        IData/*31:0*/ IDU_init__DOT__alu_src2;
        IData/*31:0*/ IDU_init__DOT__next_pc_jump;
        IData/*31:0*/ IDU_init__DOT__rs1;
        IData/*31:0*/ IDU_init__DOT__rs2;
        IData/*31:0*/ IDU_init__DOT__next_pc_csr;
        IData/*31:0*/ IDU_init__DOT__imm_J;
        IData/*31:0*/ IDU_init__DOT__imm_I;
        IData/*31:0*/ IDU_init__DOT__imm_U;
        IData/*31:0*/ IDU_init__DOT__imm_S;
        IData/*31:0*/ IDU_init__DOT__imm_B;
        IData/*31:0*/ IDU_init__DOT__mstatus;
        IData/*31:0*/ IDU_init__DOT__mtvec;
        IData/*31:0*/ IDU_init__DOT__mepc;
        IData/*31:0*/ IDU_init__DOT__mcause;
        IData/*31:0*/ IDU_init__DOT__csr_temp;
        IData/*31:0*/ IDU_init__DOT__csr2reg;
        IData/*31:0*/ IDU_init__DOT__mvendorid;
        IData/*31:0*/ IDU_init__DOT__marchid;
        IData/*31:0*/ IDU_init__DOT__gpr_wdata_total;
        IData/*31:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__gpr_wdata;
        IData/*31:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__gpr_rdata1;
        IData/*31:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__gpr_rdata2;
        IData/*31:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__j;
        IData/*31:0*/ IDU_init__DOT__ysyx_25080218_GPR_init__DOT__i;
        IData/*31:0*/ IFU_init__DOT__next_pc_jump;
        IData/*31:0*/ IFU_init__DOT__branch_pc;
        IData/*31:0*/ IFU_init__DOT__next_pc_csr;
        IData/*31:0*/ IFU_init__DOT__npc;
        IData/*31:0*/ IFU_init__DOT__pc;
        IData/*31:0*/ IFU_init__DOT__inst;
        IData/*31:0*/ IFU_init__DOT__ARADDR;
        IData/*31:0*/ IFU_init__DOT__RDATA;
        IData/*31:0*/ IFU_init__DOT__next_pc;
        IData/*31:0*/ IFU_init__DOT__araddr_latched;
        IData/*31:0*/ EXU_init__DOT__alu_src1;
        IData/*31:0*/ EXU_init__DOT__alu_src2;
        IData/*31:0*/ EXU_init__DOT__rs1;
        IData/*31:0*/ EXU_init__DOT__rs2;
        IData/*31:0*/ EXU_init__DOT__alu_result;
        IData/*31:0*/ EXU_init__DOT__branch_pc;
        IData/*31:0*/ EXU_init__DOT__alu_a;
        IData/*31:0*/ EXU_init__DOT__alu_b;
        IData/*31:0*/ EXU_init__DOT____VdfgRegularize_he932f07c_0_1;
        IData/*31:0*/ MAU_init__DOT__data;
        IData/*31:0*/ MAU_init__DOT__addr;
        IData/*31:0*/ MAU_init__DOT__rdata;
        IData/*31:0*/ MAU_init__DOT__AWADDR;
        IData/*31:0*/ MAU_init__DOT__WDATA;
        IData/*31:0*/ MAU_init__DOT__ARADDR;
    };
    struct {
        IData/*31:0*/ MAU_init__DOT__RDATA;
        IData/*31:0*/ MAU_init__DOT__wdata;
        IData/*31:0*/ MAU_init__DOT__rdata_r;
        IData/*31:0*/ MAU_init__DOT__araddr_latched;
        IData/*31:0*/ WBU_init__DOT__rdata;
        IData/*31:0*/ WBU_init__DOT__alu_result;
        IData/*31:0*/ WBU_init__DOT__gpr_wdata;
        IData/*31:0*/ Cache_init__DOT__out_araddr;
        IData/*31:0*/ Cache_init__DOT__in_araddr;
        IData/*31:0*/ Cache_init__DOT__in_rdata;
        IData/*31:0*/ Cache_init__DOT__out_rdata;
        IData/*31:0*/ Cache_init__DOT__data;
        IData/*25:0*/ Cache_init__DOT__tag;
        IData/*31:0*/ Cache_init__DOT__addr;
        IData/*31:0*/ Cache_init__DOT__i;
        IData/*31:0*/ xbar_init__DOT__m1_awaddr;
        IData/*31:0*/ xbar_init__DOT__m1_wdata;
        IData/*31:0*/ xbar_init__DOT__m1_araddr;
        IData/*31:0*/ xbar_init__DOT__m1_rdata;
        IData/*31:0*/ xbar_init__DOT__m0_awaddr;
        IData/*31:0*/ xbar_init__DOT__m0_wdata;
        IData/*31:0*/ xbar_init__DOT__m0_araddr;
        IData/*31:0*/ xbar_init__DOT__m0_rdata;
        IData/*31:0*/ xbar_init__DOT__s0_awaddr;
        IData/*31:0*/ xbar_init__DOT__s0_wdata;
        IData/*31:0*/ xbar_init__DOT__s0_araddr;
        IData/*31:0*/ xbar_init__DOT__s0_rdata;
        IData/*31:0*/ xbar_init__DOT__s1_awaddr;
        IData/*31:0*/ xbar_init__DOT__s1_wdata;
        IData/*31:0*/ xbar_init__DOT__s1_araddr;
        IData/*31:0*/ xbar_init__DOT__s1_rdata;
        IData/*31:0*/ clint_init__DOT__s_awaddr;
        IData/*31:0*/ clint_init__DOT__s_wdata;
        IData/*31:0*/ clint_init__DOT__s_araddr;
        IData/*31:0*/ clint_init__DOT__s_rdata;
        IData/*31:0*/ clint_init__DOT__s_araddr_r;
        IData/*31:0*/ __VdfgRegularize_h628f4167_0_0;
        IData/*31:0*/ __Vdly__pc;
        QData/*63:0*/ clint_init__DOT__mtime;
        VlUnpacked<IData/*31:0*/, 32> IDU_init__DOT__ysyx_25080218_GPR_init__DOT__GPR;
        VlUnpacked<IData/*31:0*/, 32> IDU_init__DOT__ysyx_25080218_GPR_init__DOT__GPR_diff;
        VlUnpacked<QData/*32:0*/, 16> Cache_init__DOT__cache_data;
        VlUnpacked<IData/*25:0*/, 16> Cache_init__DOT__cache_tag;
    };

    // INTERNAL VARIABLES
    VysyxSoCFull__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ IFU_init__DOT__S_AR = 0U;
    static constexpr IData/*31:0*/ IFU_init__DOT__S_R = 1U;
    static constexpr IData/*31:0*/ MAU_init__DOT__S_IDLE = 0U;
    static constexpr IData/*31:0*/ MAU_init__DOT__S_AR = 1U;
    static constexpr IData/*31:0*/ MAU_init__DOT__S_R = 2U;
    static constexpr IData/*31:0*/ MAU_init__DOT__S_AW_W = 3U;
    static constexpr IData/*31:0*/ MAU_init__DOT__S_B = 4U;
    static constexpr IData/*31:0*/ Cache_init__DOT__DAT_LEN = 0x00000020U;
    static constexpr IData/*31:0*/ Cache_init__DOT__TAG_LEN = 0x0000001aU;
    static constexpr IData/*31:0*/ Cache_init__DOT__CACHE_SIZE = 4U;
    static constexpr IData/*31:0*/ Cache_init__DOT__BLOCK_SIZE = 2U;
    static constexpr IData/*31:0*/ Cache_init__DOT__idle = 0U;
    static constexpr IData/*31:0*/ Cache_init__DOT__AR = 1U;
    static constexpr IData/*31:0*/ Cache_init__DOT__R = 2U;

    // CONSTRUCTORS
    VysyxSoCFull_ysyx_25080218(VysyxSoCFull__Syms* symsp, const char* v__name);
    ~VysyxSoCFull_ysyx_25080218();
    VL_UNCOPYABLE(VysyxSoCFull_ysyx_25080218);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
